### ISSUE TITLE
Remoção de código desnecessário

### ISSUE THREAD

**Issue by GustavoStorch** [schneiderjaoo/hub#12]
https://github.com/schneiderjaoo/hub/blob/967f3f96e25e041935c44390d17ad6e82d2c8091/src/main/java/com/room/hub/bean/Salas.java#L59C5-L87C6

É possível realizar a remoção do código acima, tendo em vista que está sendo utilizado a biblioteca lombook que já realiza as funções de getters, setters e construtores.

**Comment by schneiderjaoo** [comment]
Após análise foi visto que apenas as funções de associar/desassociar seria necessário manter, o restante foi retirado e já foi arrumado na própria SalasAPI

Commit: Salas/SalasAPI[https://github.com/schneiderjaoo/hub/commit/35cd922ed1dfc5ad299df8336127e1813299bd77](url)

**Comment by schneiderjaoo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues GitHub](https://trello.com/c/xGPLFo6M/75-issues-github)
