### ISSUE TITLE
Remoção de código desnecessário

### ISSUE THREAD

**Issue by GustavoStorch** [schneiderjaoo/hub#13]
https://github.com/schneiderjaoo/hub/blob/967f3f96e25e041935c44390d17ad6e82d2c8091/src/main/java/com/room/hub/bean/Clientes.java#L43-L61

É possível realizar a remoção do código acima, tendo em vista que está sendo utilizado a biblioteca lombook que já realiza as funções de getters, setters e construtores.

**Comment by schneiderjaoo** [comment]
Após a revisão do código, foi decidido manter apenas as funções alteraNomeCliente, alteraSenha e setSalas, pois as demais não representavam duplicidade, já que funcionavam de forma independente dos setters. Assim, mantivemos apenas o que é necessário de acordo com a regra de negócio definida, removendo o que não era mais relevante

Link da alteração: [commit](https://github.com/schneiderjaoo/hub/commit/d1b2f6a88edd5d6988c0d9b39f7dd4f9ba5f858c)

**Comment by schneiderjaoo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues GitHub](https://trello.com/c/xGPLFo6M/75-issues-github)
