### ISSUE TITLE
 Comentário desnecessário

### ISSUE THREAD

**Issue by GustavoStorch** [schneiderjaoo/hub#14]
https://github.com/schneiderjaoo/hub/blob/967f3f96e25e041935c44390d17ad6e82d2c8091/src/main/java/com/room/hub/dao/SalasRepository.java#L10-L12

Não é necessário a consulta para buscar o próximo ID, também não é necessário manter o comentário pois estará deixando o código sujo.

**Comment by schneiderjaoo** [comment]
Ao analisar o código foi visto que essa função seria para gerar um id novo sempre que criasse uma sala.
Mas ao rever o código foi implementado a função GeneratedValue e dessa forma se tornou desnecessário a utilização dessa função comentada e foi feita s sua remoção.

Commit [SalasRepository](https://github.com/schneiderjaoo/hub/commit/2a223a74864e1c131944edfd234a9e7b49038826)

**Comment by schneiderjaoo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues GitHub](https://trello.com/c/xGPLFo6M/75-issues-github)
