### ISSUE TITLE
Verificar necessidade de implementação novamente.

### ISSUE THREAD

**Issue by GustavoStorch** [schneiderjaoo/hub#15]
https://github.com/schneiderjaoo/hub/blob/967f3f96e25e041935c44390d17ad6e82d2c8091/src/main/java/com/room/hub/service/SalasService.java#L16-L20

**Comment by schneiderjaoo** [comment]
Durante a análise, constatou-se que já possuímos uma implementação mais robusta, que fornece um ID sem a necessidade do método anteriormente mencionado, o qual, inclusive, já foi removido do código. Dessa forma, procedemos com a exclusão definitiva do método.

**Comment by schneiderjaoo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues GitHub](https://trello.com/c/xGPLFo6M/75-issues-github)
